# Generated by Django 3.2.4 on 2021-07-23 22:39

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_auto_20210723_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleados',
            options={'verbose_name': 'Empleado', 'verbose_name_plural': 'Empleados'},
        ),
        migrations.AddField(
            model_name='empleados',
            name='cv',
            field=ckeditor.fields.RichTextField(default='cv vacio'),
            preserve_default=False,
        ),
    ]
