# Generated by Django 3.2.4 on 2021-07-22 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pruebabbdd',
            old_name='catidad',
            new_name='cantidad',
        ),
    ]
