# Generated by Django 3.2.4 on 2021-07-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departamento',
            name='apellidos',
        ),
        migrations.AddField(
            model_name='departamento',
            name='nombreCorto',
            field=models.CharField(default=None, max_length=50, verbose_name='Nombre corto'),
        ),
    ]
